import bpy, math, random, json
from pathlib import Path
from mathutils import Vector
ROOT=Path('/Users/metapro/Desktop/unitiproperty'); OUT=ROOT/'output'
bpy.ops.wm.open_mainfile(filepath=str(OUT/'satMap_3D_blue_confirmed.blend'))
random.seed(43)
def material(name,color,rough=.8):
 m=bpy.data.materials.new(name);m.diffuse_color=(*color,1);m.use_nodes=True
 b=m.node_tree.nodes.get('Principled BSDF');b.inputs['Base Color'].default_value=(*color,1);b.inputs['Roughness'].default_value=rough
 return m
cream=material('Architecture | ivory plaster',(.78,.76,.65)); concrete=material('Architecture | concrete',(.43,.46,.43))
roofmat=material('Architecture | terracotta roof',(.48,.20,.105)); metal=material('Architecture | standing seam roof',(.36,.43,.43))
glass=material('Architecture | dark blue glazing',(.075,.17,.21),.23);trim=material('Architecture | window frames',(.77,.80,.74))
asphalt=material('Road | weathered asphalt',(.18,.20,.19)); shoulder=material('Road | gravel shoulder',(.52,.51,.42));mark=material('Road | faded markings',(.79,.78,.65))
bark=material('Trees | bark',(.22,.16,.095));leaf=[material('Trees | foliage '+str(i),c) for i,c in enumerate([(.12,.25,.085),(.20,.32,.105),(.27,.37,.14),(.10,.21,.075)])]
water=material('Sea | coastal water',(.21,.42,.43),.26)
def collection(name):
 c=bpy.data.collections.new(name);bpy.context.scene.collection.children.link(c);return c
architecture=collection('01 | Campus buildings'); roads=collection('02 | Confirmed road and access'); vegetation=collection('03 | Coastal vegetation'); details=collection('04 | Site details')
def move(o,c):
 for old in list(o.users_collection):old.objects.unlink(o)
 c.objects.link(o);return o
def cube(name,loc,dim,mat,col=architecture):
 bpy.ops.mesh.primitive_cube_add(size=1,location=loc);o=bpy.context.object;o.name=name;o.dimensions=dim;bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);o.data.materials.append(mat);move(o,col);return o
def mesh(name,v,f,mat,col):
 m=bpy.data.meshes.new(name);m.from_pydata(v,[],f);m.update();o=bpy.data.objects.new(name,m);col.objects.link(o);m.materials.append(mat);return o
def xy(p,z=.65):return Vector(((p[0]-684.5)/10,(384-p[1])/10,z))
# Keep the accepted parcel geometry, remove only previous illustrative objects.
for o in list(bpy.data.objects):
 if o.name.startswith(('Campus building','Campus roof','Vegetation •')):bpy.data.objects.remove(o,do_unlink=True)
# Ownership is an overlay, not a physical wall or raised building platform.
for o in list(bpy.data.objects):
 if o.name=='UNITI SDN BHD • raised parcel edges':bpy.data.objects.remove(o,do_unlink=True)
 elif o.name=='UNITI SDN BHD • ownership parcel from boundMap':
  for v in o.data.vertices:v.co.z=.661
 elif o.name=='UNITI SDN BHD • complete ownership boundary':
  o.data.bevel_depth=.045
  for sp in o.data.splines:
   for p in sp.points:p.co.z=.725
 elif o.name=='Site perimeter • traced from dashed boundary':o.data.bevel_depth=.065
for m in bpy.data.materials:
 if m.name.startswith('UNITI parcel'):
  for n in m.node_tree.nodes:
   if n.type=='MIX_RGB':n.inputs[0].default_value=.12

boundary=[(426,333),(433,286),(460,234),(499,182),(519,183),(571,230),(631,251),(623,261),(677,294),(734,342),(741,334),(793,392),(818,403),(903,432),(881,472),(933,494),(946,477),(1008,503),(910,610),(887,620),(865,622),(842,614),(818,591),(782,505),(713,422),(553,350)]
def inside(x,y,poly=boundary):
 hit=False;j=len(poly)-1
 for i,(a,b) in enumerate(poly):
  c,d=poly[j]
  if (b>y)!=(d>y) and x<(c-a)*(y-b)/(d-b)+a:hit=not hit
  j=i
 return hit
road=list(reversed(json.loads((OUT/'blue_road_trace.json').read_text())))
# Dense annotation contains hand-drawn jitter: preserve its actual course.
def ribbon(name,points,width,z,mat):
 v=[]
 for i,p in enumerate(points):
  a=xy(points[max(0,i-1)]);b=xy(points[min(len(points)-1,i+1)]);d=(b-a).normalized();n=Vector((-d.y,d.x,0));c=xy(p,z)
  v.extend([tuple(c-n*width/2),tuple(c+n*width/2)])
 return mesh(name,v,[(2*i,2*i+1,2*i+3,2*i+2) for i in range(len(points)-1)],mat,roads)
ribbon('Boundary road | gravel verges',road,.69,.685,shoulder)
ribbon('Boundary road | asphalt surface',road,.46,.698,asphalt)
# Dashes are generated by arc length rather than by annotation sampling density.
path=[xy(p,.706) for p in road];distance=0;next_dash=.8
for a,b in zip(path,path[1:]):
 length=(b-a).length
 while next_dash<distance+length:
  t=(next_dash-distance)/length;c=a+(b-a)*t;o=cube('Road centre dash',c,(.028,.19,.004),mark,roads);o.rotation_euler.z=math.atan2((b-a).y,(b-a).x)-math.pi/2;next_dash+=.7
 distance+=length
access=[[(499,191),(483,220),(471,241),(475,251)],[(478,252),(504,246),(536,259),(552,272)],[(552,272),(578,262),(605,272)]]
for i,p in enumerate(access):ribbon('Campus access '+str(i+1),p,.36,.695,asphalt)

# Detailed, editable architecture at visible roof clusters. Heights remain indicative.
footprints=[]
buildings=[(507,212,25,8,-35,1.00),(520,224,29,8,-35,1.00),(533,236,28,8,-35,1.00),(486,246,25,10,-15,.85),(479,261,24,10,-15,.85),(574,247,25,14,-20,1.45),(599,260,18,12,-20,1.10),(553,256,20,9,-20,.85),(509,239,14,7,-35,.65)]
def building(i,x,y,w,d,angle,h):
 cx,cy,z=xy((x,y));w/=10;d/=10;angle=math.radians(angle);footprints.append((x,y,max(w,d)*5+7))
 def world(lx,ly,lz):return (cx+lx*math.cos(angle)-ly*math.sin(angle),cy+lx*math.sin(angle)+ly*math.cos(angle),.665+lz)
 def part(name,pos,dim,ma):
  o=cube(f'{i:02d} | '+name,world(*pos),dim,ma);o.rotation_euler.z=angle;return o
 part('foundation',(0,0,.06),(w+.12,d+.12,.12),concrete)
 part('walls',(0,0,h/2+.1),(w,d,h),cream)
 rh=min(.38,d*.38);e=.09
 v=[world(-w/2-e,-d/2-e,h+.10),world(w/2+e,-d/2-e,h+.10),world(w/2+e,d/2+e,h+.10),world(-w/2-e,d/2+e,h+.10),world(-w/2-e,0,h+.1+rh),world(w/2+e,0,h+.1+rh)]
 mesh(f'{i:02d} | pitched roof',v,[(0,1,5,4),(4,5,2,3),(0,4,3),(1,2,5)],roofmat if i<8 else metal,architecture)
 # Ridge cap and repeated roof seams create readable depth in close views.
 part('ridge cap',(0,0,h+.1+rh),(w+.2,.055,.045),roofmat)
 floors=max(1,round(h/.48));count=max(3,int(w/.34))
 for floor in range(floors):
  for j in range(count):
   xx=-w/2+(j+.5)*w/count;zz=.24+floor*h/floors
   for side in [-1,1]:
    part('window frame',(xx,side*(d/2+.013),zz),(.20,.025,.24),trim)
    part('glazing',(xx,side*(d/2+.029),zz),(.155,.014,.19),glass)
 part('entry door',(0,-d/2-.026,.25),(.18,.024,.36),glass)
 part('entry canopy',(0,-d/2-.19,.65),(.55,.4,.045),metal)
 for xx in [-.22,.22]:part('canopy column',(xx,-d/2-.31,.33),(.035,.035,.65),cream)
 for side in [-1,1]:part('rain gutter',(0,side*(d/2+.095),h+.08),(w+.18,.045,.055),metal)
for i,b in enumerate(buildings,1):building(i,*b)

# Reusable trees: actual trunks, branches and multi-lobed canopies, plus palms.
def cylinder(name,a,b,r,ma,col=vegetation):
 a=Vector(a);b=Vector(b);bpy.ops.mesh.primitive_cone_add(vertices=7,radius1=r,radius2=r*.65,depth=(b-a).length,location=(a+b)/2);o=bpy.context.object;o.name=name;o.rotation_euler=(b-a).to_track_quat('Z','Y').to_euler();o.data.materials.append(ma);move(o,col);return o
parts=[]
parts.append(cylinder('Trunk',(0,0,0),(0,0,.85),.055,bark))
for k in range(5):
 a=k*2.399;px=.24*math.cos(a);py=.24*math.sin(a);pz=.8+.13*(k%3)
 parts.append(cylinder('Branch',(0,0,.48),(px,py,pz),.028,bark))
 bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=2,radius=.36,location=(px,py,pz+.2));o=bpy.context.object;o.scale=(1,1,1.05);o.data.materials.append(leaf[k%4]);move(o,vegetation);parts.append(o)
bpy.ops.object.select_all(action='DESELECT')
for o in parts:o.select_set(True)
bpy.context.view_layer.objects.active=parts[0];bpy.ops.object.join();tree=bpy.context.object;tree.name='Broadleaf tree template';tree_data=tree.data.copy();tree_origin=tree.location.copy();bpy.data.objects.remove(tree,do_unlink=True)
# Palm mesh in local coordinates with drooping, narrow fronds.
v=[];f=[];mi=[]
for z,r in [(0,.052),(.95,.033)]:
 for k in range(8):v.append((r*math.cos(k*math.pi/4),r*math.sin(k*math.pi/4),z))
for k in range(8):f.append((k,(k+1)%8,(k+1)%8+8,k+8));mi.append(0)
for k in range(9):
 a=k*2*math.pi/9;start=len(v)
 for j in range(6):
  t=j/5;rr=.65*t;zz=.97+.27*math.sin(t*math.pi)-.12*t;width=.095*math.sin(math.pi*t)+.006
  for side in [-1,1]:v.append((rr*math.cos(a)+side*width*math.sin(a),rr*math.sin(a)-side*width*math.cos(a),zz))
 for j in range(5):f.append((start+2*j,start+2*j+1,start+2*j+3,start+2*j+2));mi.append(1+k%3)
po=mesh('Palm template',v,f,bark,vegetation)
for m in leaf[:3]:po.data.materials.append(m)
for face,idx in zip(po.data.polygons,mi):face.material_index=idx
palm_data=po.data;bpy.data.objects.remove(po,do_unlink=True)
# Use satellite colour to reject clearings, roofs and bare earth, and keep all roads open.
image=bpy.data.images.get('satMap.png');pix=list(image.pixels);iw,ih=image.size
allroads=[road]+access
def road_distance(x,y):
 best=1e9
 for points in allroads:
  for a,b in zip(points,points[1:]):
   dx=b[0]-a[0];dy=b[1]-a[1];t=max(0,min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy+1e-10)))
   best=min(best,math.hypot(x-a[0]-t*dx,y-a[1]-t*dy))
 return best
placed=[]
for attempt in range(18000):
 x=random.uniform(436,995);y=random.uniform(275,615)
 if not inside(x,y) or road_distance(x,y)<6.5:continue
 if any(math.hypot(x-a,y-b)<r+4 for a,b,r in footprints):continue
 if any((x-a)**2+(y-b)**2<6.7**2 for a,b in placed):continue
 idx=(min(ih-1,max(0,int(ih-1-y)))*iw+min(iw-1,int(x)))*4;r,g,b=pix[idx:idx+3]
 if g<r*1.015 or g<b*1.045 or max(r,g,b)>.70:continue
 if x>857 and y>509:continue
 placed.append((x,y));palm=(x>575 and random.random()<.44)
 o=bpy.data.objects.new(('Palm' if palm else 'Coastal broadleaf')+f' {len(placed):03}',palm_data if palm else tree_data);vegetation.objects.link(o)
 o.location=xy((x,y),.665)+(Vector((0,0,0)) if palm else tree_origin);s=random.uniform(.72,1.18);o.scale=(s,s,s*random.uniform(.85,1.2));o.rotation_euler.z=random.uniform(0,6.28)
 if len(placed)>=580:break
# Small roadside lighting along the campus segment only.
for p in road[5:48:12]:
 q=xy(p,.67);q.x-=.4;cylinder('Campus light pole',q,q+Vector((0,0,.72)),.018,metal,details);cube('Campus light head',q+Vector((0,0,.73)),(.14,.075,.035),trim,details)
# Make the water texture respond to light without inventing a new shoreline.
sat=bpy.data.materials.get('Satellite image • original georeferenced by image pixels')
# Scene hierarchy and useful metadata.
scene=bpy.context.scene;scene['Detail notes']='Confirmed blue boundary retained. Road follows extracted annotation. Building positions follow visible roof clusters; facade details and heights are illustrative. Vegetation placement filtered by satellite vegetation colour and road/building clearance.'
scene['Tree count']=len(placed)
scene.render.engine='CYCLES';scene.cycles.samples=48;scene.cycles.use_denoising=True
scene.view_settings.view_transform='AgX';scene.render.resolution_x=2000;scene.render.resolution_y=1500
cam=scene.camera;cam.location=(72,-98,124);target=Vector((1.5,-.5,.7));cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.ortho_scale=100
for screen in bpy.data.screens:
 for area in screen.areas:
  if area.type=='VIEW_3D':
   area.spaces.active.region_3d.view_perspective='CAMERA';area.spaces.active.overlay.show_overlays=False
bpy.ops.object.select_all(action='DESELECT')
scene.render.filepath=str(OUT/'satMap_3D_detailed.png')
bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'satMap_3D_detailed.blend'))
bpy.ops.render.render(write_still=True)
# Close-up proves the buildings and road have real geometric detail.
cam.location=(0,-26,65);target=xy((535,252));cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.ortho_scale=26
scene.render.filepath=str(OUT/'satMap_campus_detail.png');bpy.ops.render.render(write_still=True)
print('DETAIL COMPLETE',len(buildings),'buildings',len(placed),'trees')
